### ISSUE TITLE
cannot pack file

### ISSUE THREAD

**Issue by andy2046** [commenthol/offline-npm#10]
D:\react-app-boilerplate-master>offline-npm --add
    offline-npm was added to project: react-app-boilerplate

D:\react-app-boilerplate-master>npm pack

> react-app-boilerplate@0.1.4 prepublish D:\react-app-boilerplate-master
> ./offline/offline-npm --prepublish ;

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! addLocal Could not install D:\react-app-boilerplate-master

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'pack' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 silly cache add args [ '.', null ]
5 verbose cache add spec .
6 silly cache add parsed spec Result {
6 silly cache add   raw: '.',
6 silly cache add   scope: null,
6 silly cache add   escapedName: null,
6 silly cache add   name: null,
6 silly cache add   rawSpec: '.',
6 silly cache add   spec: 'D:\react-app-boilerplate-master',
6 silly cache add   type: 'directory' }
7 verbose addLocalDirectory C:\Users\user\AppData\Roaming\npm-cache\react-app-boilerplate\0.1.4\package.tgz not in flight; packing
8 verbose correctMkdir C:\Users\user\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
9 info lifecycle react-app-boilerplate@0.1.4~prepublish: react-app-boilerplate@0.1.4
10 verbose lifecycle react-app-boilerplate@0.1.4~prepublish: unsafe-perm in lifecycle true
11 verbose lifecycle react-app-boilerplate@0.1.4~prepublish: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\react-app-boilerplate-master\node_modules.bin;C:\Program Files\nodejs;C:\Program Files\Java\jdk1.8.0_102\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\Users\user\AppData\Local\atom\bin;C:\Users\user\AppData\Roaming\npm
12 verbose lifecycle react-app-boilerplate@0.1.4~prepublish: CWD: D:\react-app-boilerplate-master
13 silly lifecycle react-app-boilerplate@0.1.4~prepublish: Args: [ '/d /s /c', './offline/offline-npm --prepublish ; ' ]
14 silly lifecycle react-app-boilerplate@0.1.4~prepublish: Returned: code: 1  signal: null
15 info lifecycle react-app-boilerplate@0.1.4~prepublish: Failed to exec prepublish script
16 error addLocal Could not install D:\react-app-boilerplate-master
17 verbose stack Error: react-app-boilerplate@0.1.4 prepublish: `./offline/offline-npm --prepublish ;`
17 verbose stack Exit status 1
17 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
17 verbose stack     at emitTwo (events.js:106:13)
17 verbose stack     at EventEmitter.emit (events.js:191:7)
17 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
17 verbose stack     at emitTwo (events.js:106:13)
17 verbose stack     at ChildProcess.emit (events.js:191:7)
17 verbose stack     at maybeClose (internal/child_process.js:877:16)
17 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
18 verbose pkgid react-app-boilerplate@0.1.4
19 verbose cwd D:\react-app-boilerplate-master
20 error Windows_NT 6.2.9200
21 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "pack"
22 error node v6.5.0
23 error npm  v3.10.3
24 error code ELIFECYCLE
25 error react-app-boilerplate@0.1.4 prepublish: `./offline/offline-npm --prepublish ;`
25 error Exit status 1
26 error Failed at the react-app-boilerplate@0.1.4 prepublish script './offline/offline-npm --prepublish ; '.
26 error Make sure you have the latest version of node.js and npm installed.
26 error If you do, this is most likely a problem with the react-app-boilerplate package,
26 error not with npm itself.
26 error Tell the author that this fails on your system:
26 error     ./offline/offline-npm --prepublish ;
26 error You can get information on how to open an issue for this project with:
26 error     npm bugs react-app-boilerplate
26 error Or if that isn't available, you can get their info via:
26 error     npm owner ls react-app-boilerplate
26 error There is likely additional logging output above.
27 verbose exit [ 1, true ]

**Comment by commenthol** [comment]
Sorry for this, but this project is not supported on Windows. The problem lies in the modified `package.json`
```
  "preinstall": "./offline/offline-npm --preinstall & sleep 2 ; "
```
npm needs to be "halted" for some time to make sure the "fake" registry server has been started.
