### ISSUE TITLE
Error using offline-npm -add in Windows 

### ISSUE THREAD

**Issue by billyberjas** [commenthol/offline-npm#3]
Hi, I´m trying to use offline-npm in windows 7 and I got the following error using the command `offline-npm-add`

User has permissions to write on `C:\Users\scia\source\Products\WebPortal\application` folder

offline-npm package was installed globally using `offline-npm --add` 

`C:\Users\scia\source\Products\WebPortal\application>offline-npm -add
fs.js:747
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'C:\C:'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at C:\Users\scia\AppData\Roaming\npm\node_modules\offline-npm\offline-npm.js
:47:7
    at Array.forEach (native)
    at mkdir (C:\Users\scia\AppData\Roaming\npm\node_modules\offline-npm\offline
-npm.js:44:7)
    at C:\Users\scia\AppData\Roaming\npm\node_modules\offline-npm\offline-npm.js
:764:7
    at C:\Users\scia\AppData\Roaming\npm\node_modules\offline-npm\offline-npm.js
:351:12
    at C:\Users\scia\AppData\Roaming\npm\node_modules\offline-npm\offline-npm.js
:325:13
    at FSReqWrap.oncomplete (fs.js:95:15)`

Thanks

**Comment by commenthol** [comment]
Hi billyberjas, I do not have windows at hands, but I hope having found the lines of trouble.
I just published `offline@0.1.6-0`. Would you mind to install that version from npm and give it a try.
Please let me know your findings. Thanks.

**Comment by billyberjas** [comment]
Yes! It did work! Thanks for your fast response :D
