### ISSUE TITLE
Is this compatible with Windows?

### ISSUE THREAD

**Issue by nford** [commenthol/offline-npm#4]
Failing with this error when running 'npm pack'. Any ideas? Using Windows 7, Node 4.1.0, NPM 2.14.3

> ./offline/offline-npm --prepublish ;

>'.' is not recognized as an internal or external command,
>operable program or batch file.

**Comment by commenthol** [comment]
I never tried with Windows by myself. Sorry for that. @billyberjas reported success in #3.

**Comment by mastuart** [comment]
I'm running 'npm install' on the tgz file in Windows and says "Failed to exec preinstall script"

preinstall: `./offline/offline-npm --preinstall & sleep 2 ; 

Also, I'm using a Mac to run 'npm pack' but, when I decompress the file I'm not seeing the 'offline' folder inside of it. Thoughts?

**Comment by commenthol** [comment]
I can't reproduce the problem on OSX. Please run `npm test` and report the problem if any.
Please note before you run `npm pack` the command `offline-npm -a` needs to be applied successfully such changing `package.json` file. 

To be honest I doubt that running on Win works. I cannot imagine that `& sleep 2` really works there.

You could try the following in your `package.json`

1. Run `offline-npm -a`
2. Edit `package.json` and change

        "scripts": {
          "test": "echo \"Error: no test specified\" && exit 1",
          "prepublish": "node offline/offline-npm --prepublish ; ",
          "preinstall": "node offline/offline-npm --preinstall & timeout 2 ; ",
          "postinstall": "node offline/offline-npm --postinstall ; "
        },

**Comment by commenthol** [comment]
This project is confirmed to not run in Windows.
