### ISSUE TITLE
offline-npm needs network connection to be installed, even with npmunbox

### ISSUE THREAD

**Issue by loiclacombe** [commenthol/offline-npm#6]
Hi,
I have tried to install offline-npm with npmunbox as I must install an offline npm registry, on a server which has no internet access and will never have for security reasons.
So, I have installed it with npmunbox but was deeply disapointed that offline-npm tries to connect to the registry on its install, which kind of defeats its purpose.

**Comment by commenthol** [comment]
Hi, I have never used npmunbox with offline-npm. To my believe, it is not a good idea, of using two tools trying to solve the same at the same time. I have not understood why you do not use npmunbox/ offline-npm only? If your problem persists with using only this project please report the npm-debug.log file or the npm/node versions you are using on your offline machine.

**Comment by loiclacombe** [comment]
I needed to install offline-npm while offline. So AFAIK, the only way to do this is to download the packages from another computer with npmbox, then transfer the resulting file and install it on the target machine.
In the end, the only viable setup I could make was with a Sonatype Nexus server. It can be installed offline, and installations (proxy cache included) can be transferred to an offline machine.
