### ISSUE TITLE
Error encountered in tutorial

### ISSUE THREAD

**Issue by alicanerdogan** [commenthol/offline-npm#8]
There is an error in Install Offline section at [https://github.com/commenthol/offline-npm/blob/master/TUTORIAL.md#install-offline](https://github.com/commenthol/offline-npm/blob/master/TUTORIAL.md#install-offline) after npm install command.

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "try-0.0.0.tgz"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ENOSELF

npm ERR! Refusing to install try as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ae/Repos/npm-server/offline-npm/try/try-offline/npm-debug.log
```

**Comment by commenthol** [comment]
Hi thanks for your notice. Yes indeed npm@3.9 causes problems with node@6.2 using this project.
On upgrading npm to v3.10.3 with `npm i -g npm` all is fine.

**Comment by commenthol** [comment]
Yes indeed support for this project is broken with npm@3. I have made some simple tests which prove this. Seams that I overlooked something with my previous test 11days ago with offline-npm running in the background. Sorry for not having better news.
